name: Download Artifacts

on:
  workflow_dispatch:
    inputs:
      artifact_version:
        description: Artifact Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts-${{ github.event.inputs.image_version }}
          
